#!/usr/bin/env bash

source ./common

if [[ ! -d "$BUILD_DIR/" ]] ; then mkdir "$BUILD_DIR/" ; fi &&
if [[ ! -d "$BUILD_OBJ_DIR/" ]] ; then mkdir "$BUILD_OBJ_DIR/" ; fi &&
if [[ ! -d "$BUILD_LIB_DIR/" ]] ; then mkdir "$BUILD_LIB_DIR/" ; fi &&

for src_file in "src/"*.c ; do
	src_file_basename="$(basename -s ".c" "$src_file")" &&
	$CC -o "$BUILD_OBJ_DIR/$src_file_basename.o" -c "$src_file" \
		|| exit 70 # EX_SOFTWARE
done &&
$AR -c "$BUILD_LIB_DIR/$LIBRARY_NAME.a" "$BUILD_OBJ_DIR/"*.o &&

exit 0 # EX_OK
