#!/bin/bash

CC="cc -std=c99 -O -Wall"
AR="ar -rs"

export LIBRARY_PATH="/opt/local/lib:$LIBRARY_PATH"
export C_INCLUDE_PATH="/opt/local/include:$C_INCLUDE_PATH"

BUILD_DIR="output"

[[ -d "$BUILD_DIR/" ]] || mkdir "$BUILD_DIR/"
[[ -d "$BUILD_DIR/obj/" ]] || mkdir "$BUILD_DIR/obj/"
[[ -d "$BUILD_DIR/lib/" ]] || mkdir "$BUILD_DIR/lib/"

$CC -o "$BUILD_DIR/obj/sbuf.o" -c src/sbuf.c
$AR -c "$BUILD_DIR/lib/libsbuf.a" "$BUILD_DIR/obj/"*.o
